export const BALANCED_QUERY_PHRASES = [
  "pros and cons",
  "positive and negative",
  "good and bad",
  "strengths and weaknesses",
  "advantages and disadvantages",
];

export const NEGATIVE_QUERY_PHRASES = [
  "do not like",
  "don't like",
  "did not like",
  "didn't like",
  "not good",
  "not worth",
  "went wrong",
];

export const POSITIVE_QUERY_PHRASES = [
  "works well",
  "worth buying",
  "worth it",
];

export const NEGATIVE_QUERY_TERMS = new Set([
  "bad",
  "complaint",
  "complaints",
  "concern",
  "concerns",
  "con",
  "cons",
  "damage",
  "damaged",
  "defect",
  "defective",
  "delay",
  "delayed",
  "disappointing",
  "dislike",
  "drawback",
  "drawbacks",
  "fail",
  "failed",
  "failure",
  "issue",
  "issues",
  "late",
  "negative",
  "poor",
  "problem",
  "problems",
  "refund",
  "return",
  "risk",
  "risks",
  "worse",
  "worst",
]);

export const POSITIVE_QUERY_TERMS = new Set([
  "benefit",
  "benefits",
  "best",
  "good",
  "great",
  "happy",
  "like",
  "liked",
  "likes",
  "love",
  "loved",
  "positive",
  "praise",
  "pro",
  "pros",
  "recommend",
  "satisfied",
  "strength",
  "strengths",
]);

export const OVERALL_QUERY_PHRASES = [
  "overall sentiment",
  "general sentiment",
  "general opinion",
  "general opinions",
  "general view",
  "overall opinion",
  "overall opinions",
  "overall view",
  "overall verdict",
  "common opinion",
  "people think",
  "customers think",
  "customer opinion",
  "customer opinions",
  "worth buying",
  "worth it",
  "should i buy",
  "should we buy",
  "would you recommend",
];

export const OVERALL_QUERY_TERMS = new Set([
  "consensus",
  "majority",
  "overall",
  "recommendation",
  "sentiment",
  "summary",
  "summarize",
  "takeaway",
  "verdict",
]);

export const QUERY_TYPO_REPLACEMENTS = [
  [/\bgenera\b/g, "general"],
  [/\bgenral\b/g, "general"],
  [/\bgenerl\b/g, "general"],
  [/\bopnion\b/g, "opinion"],
  [/\bopinon\b/g, "opinion"],
  [/\boppinion\b/g, "opinion"],
  [/\bsandles\b/g, "sandals"],
  [/\bsneekers\b/g, "sneakers"],
  [/\bcomfertable\b/g, "comfortable"],
  [/\bcomfortble\b/g, "comfortable"],
  [/\bqulaity\b/g, "quality"],
  [/\bqualty\b/g, "quality"],
  [/\bdurablity\b/g, "durability"],
  [/\bdelievery\b/g, "delivery"],
  [/\brelevent\b/g, "relevant"],
  [/\brecomend\b/g, "recommend"],
  [/\bcomplants\b/g, "complaints"],
];

export const QUERY_SUBJECT_FILLER_TERMS = new Set([
  "common",
  "customer",
  "customers",
  "feel",
  "feeling",
  "general",
  "opinion",
  "opinions",
  "people",
  "person",
  "product",
  "regarding",
  "review",
  "reviews",
  "think",
  "thinking",
  "thought",
  "thoughts",
  "toward",
  "towards",
  "user",
  "users",
  "view",
  "views",
]);

export const DETAILED_QUERY_TERMS = new Set([
  "breakdown",
  "compare",
  "comparison",
  "detail",
  "details",
  "example",
  "examples",
  "list",
]);

export const SOURCE_QUERY_PHRASES = [
  "exact reviews",
  "show reviews",
  "show me reviews",
  "source reviews",
  "which reviews",
];

export const RETRIEVAL_STOP_WORDS = new Set([
  "about",
  "after",
  "again",
  "also",
  "are",
  "because",
  "been",
  "but",
  "can",
  "customer",
  "customers",
  "did",
  "does",
  "for",
  "from",
  "had",
  "has",
  "have",
  "how",
  "into",
  "main",
  "most",
  "of",
  "not",
  "on",
  "people",
  "review",
  "reviews",
  "that",
  "the",
  "their",
  "them",
  "there",
  "these",
  "they",
  "this",
  "was",
  "were",
  "what",
  "when",
  "with",
]);
